// Generated by gencpp from file sreesr_pkg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SREESR_PKG_MESSAGE_ADDTWOINTS_H
#define SREESR_PKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <sreesr_pkg/AddTwoIntsRequest.h>
#include <sreesr_pkg/AddTwoIntsResponse.h>


namespace sreesr_pkg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace sreesr_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sreesr_pkg::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::sreesr_pkg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::sreesr_pkg::AddTwoInts > {
  static const char* value()
  {
    return "sreesr_pkg/AddTwoInts";
  }

  static const char* value(const ::sreesr_pkg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::sreesr_pkg::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::sreesr_pkg::AddTwoInts > 
template<>
struct MD5Sum< ::sreesr_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sreesr_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::sreesr_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sreesr_pkg::AddTwoIntsRequest> should match 
// service_traits::DataType< ::sreesr_pkg::AddTwoInts > 
template<>
struct DataType< ::sreesr_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sreesr_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::sreesr_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sreesr_pkg::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::sreesr_pkg::AddTwoInts > 
template<>
struct MD5Sum< ::sreesr_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sreesr_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::sreesr_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sreesr_pkg::AddTwoIntsResponse> should match 
// service_traits::DataType< ::sreesr_pkg::AddTwoInts > 
template<>
struct DataType< ::sreesr_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sreesr_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::sreesr_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SREESR_PKG_MESSAGE_ADDTWOINTS_H
